name: Build and deploy Node.js app to Azure Web App - integrator-backend

on:
  push:
    branches:
      - dev
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: integrator-backend
  AZURE_WEBAPP_PACKAGE_PATH: "./backend"
  NODE_VERSION: "18.x"

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{env.NODE_VERSION}}
      - name: install packages, build (if necessary), test (if exists)
        run: |
          npm install
        working-directory: ${{env.AZURE_WEBAPP_PACKAGE_PATH}}
      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{env.AZURE_WEBAPP_NAME}}
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_CD535F3EB16B44599C1B7FBA6ED90C4C }}
          package: ${{env.AZURE_WEBAPP_PACKAGE_PATH}}
    
